import { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Shuffle, Sparkles, Users, Check, ArrowRight, Building2, Briefcase, AlertCircle, RefreshCw, Loader2, Plus, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { useClients } from '@/hooks/useClients';
import { useCycles } from '@/hooks/useCycles';
import { useAllocations } from '@/hooks/useAllocations';
import { useLeadership } from '@/hooks/useLeadership';
import { toast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { coordinations as allCoordinations } from '@/data/mockData';
import { useQuery } from '@tanstack/react-query';

interface Profile {
  id: string;
  user_id: string;
  email: string;
  display_name: string | null;
  avatar_url: string | null;
}

interface GTEntry {
  client_id: string;
  role: string;
}

interface PendingAllocation {
  userId: string;
  coordinationId: string | null;
  gts: GTEntry[];
}

interface AutoSuggestion {
  userId: string;
  userName: string;
  currentCoordId: string | null;
  suggestedCoordId: string;
  reason: string;
  priority: 'high' | 'medium' | 'low';
}

export const ReallocationDialog = () => {
  const [open, setOpen] = useState(false);
  const [pendingAllocations, setPendingAllocations] = useState<PendingAllocation[]>([]);
  const [autoSuggestions, setAutoSuggestions] = useState<AutoSuggestion[]>([]);
  const [autoLoading, setAutoLoading] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [autoIteration, setAutoIteration] = useState(0);

  const { clients, gtMembers } = useClients();
  const { currentCycle } = useCycles();
  const { allocations, setAllocation: saveAllocation, fetchAllocations } = useAllocations(currentCycle?.id);
  const { positions } = useLeadership();

  const { data: profiles = [] } = useQuery({
    queryKey: ['all_profiles_for_reallocation'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('profiles')
        .select('id, user_id, email, display_name, avatar_url');
      if (error) throw error;
      return data as Profile[];
    },
  });

  const getCoordination = (id: string) => allCoordinations.find((c) => c.id === id);
  
  const getInitials = (name: string | null, email: string) => {
    if (name) return name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase();
    return email.charAt(0).toUpperCase();
  };

  const getClientName = (clientId: string) => {
    return clients.find((c) => c.id === clientId)?.name || clientId;
  };

  const getRoleLabel = (role: string) => {
    switch (role) {
      case 'director': return 'Diretor';
      case 'manager': return 'Gerente';
      case 'consultant': return 'Consultor';
      default: return role;
    }
  };

  const isLeader = (userId: string) => {
    return positions.some(p => p.user_id === userId);
  };

  const coordinatorProfiles = profiles.filter(p => !isLeader(p.user_id));

  const getCurrentAllocation = (userId: string) => {
    return allocations.find(a => a.user_id === userId);
  };

  const getCurrentGTs = (userId: string): GTEntry[] => {
    if (!currentCycle) return [];
    return gtMembers
      .filter(m => m.user_id === userId && m.cycle_id === currentCycle.id)
      .map(m => ({ client_id: m.client_id, role: m.role }));
  };

  const getPendingAllocation = (userId: string) => {
    return pendingAllocations.find(p => p.userId === userId);
  };

  const getDisplayCoordId = (userId: string) => {
    const pending = getPendingAllocation(userId);
    if (pending) return pending.coordinationId;
    return getCurrentAllocation(userId)?.coordination_id || null;
  };

  const getDisplayGTs = (userId: string): GTEntry[] => {
    const pending = getPendingAllocation(userId);
    if (pending) return pending.gts;
    return getCurrentGTs(userId);
  };

  const ensurePending = (userId: string): PendingAllocation => {
    const existing = getPendingAllocation(userId);
    if (existing) return existing;
    const currentAlloc = getCurrentAllocation(userId);
    return {
      userId,
      coordinationId: currentAlloc?.coordination_id || null,
      gts: getCurrentGTs(userId),
    };
  };

  const updatePending = (userId: string, update: Partial<PendingAllocation>) => {
    setPendingAllocations(prev => {
      const base = ensurePending(userId);
      const existingIndex = prev.findIndex(p => p.userId === userId);
      const updated = { ...base, ...update };
      if (existingIndex >= 0) {
        const newList = [...prev];
        newList[existingIndex] = updated;
        return newList;
      }
      return [...prev, updated];
    });
  };

  const handleCoordChange = (userId: string, value: string) => {
    updatePending(userId, { coordinationId: value === '__none__' ? null : value });
  };

  const handleAddGT = (userId: string) => {
    const currentGTs = getDisplayGTs(userId);
    updatePending(userId, { gts: [...currentGTs, { client_id: '', role: 'consultant' }] });
  };

  const handleRemoveGT = (userId: string, index: number) => {
    const currentGTs = getDisplayGTs(userId);
    updatePending(userId, { gts: currentGTs.filter((_, i) => i !== index) });
  };

  const handleGTClientChange = (userId: string, index: number, clientId: string) => {
    const currentGTs = [...getDisplayGTs(userId)];
    currentGTs[index] = { ...currentGTs[index], client_id: clientId };
    updatePending(userId, { gts: currentGTs });
  };

  const handleGTRoleChange = (userId: string, index: number, role: string) => {
    const currentGTs = [...getDisplayGTs(userId)];
    currentGTs[index] = { ...currentGTs[index], role };
    updatePending(userId, { gts: currentGTs });
  };

  const hasChanges = (userId: string) => {
    const pending = getPendingAllocation(userId);
    if (!pending) return false;
    
    const currentAlloc = getCurrentAllocation(userId);
    const currentGTs = getCurrentGTs(userId);
    
    const coordChanged = pending.coordinationId !== (currentAlloc?.coordination_id || null);
    const gtsChanged = JSON.stringify(pending.gts) !== JSON.stringify(currentGTs);
    
    return coordChanged || gtsChanged;
  };

  const getAllocationStatus = (userId: string) => {
    const coordId = getDisplayCoordId(userId);
    const gts = getDisplayGTs(userId);
    
    if (coordId && gts.length > 0) return 'complete';
    if (coordId || gts.length > 0) return 'partial';
    return 'none';
  };

  const applyManualAllocations = async () => {
    if (!currentCycle) {
      toast({ title: 'Erro', description: 'Nenhum ciclo selecionado.', variant: 'destructive' });
      return;
    }

    const changedAllocations = pendingAllocations.filter(p => hasChanges(p.userId));

    for (const alloc of changedAllocations) {
      // Save coordination
      if (alloc.coordinationId) {
        await saveAllocation(alloc.userId, currentCycle.id, alloc.coordinationId);
      }

      // Save GTs - delete all existing for this user/cycle and re-insert
      await supabase
        .from('gt_members')
        .delete()
        .eq('user_id', alloc.userId)
        .eq('cycle_id', currentCycle.id);

      const validGTs = alloc.gts.filter(gt => gt.client_id && gt.role);
      if (validGTs.length > 0) {
        await supabase.from('gt_members').insert(
          validGTs.map(gt => ({
            user_id: alloc.userId,
            client_id: gt.client_id,
            role: gt.role,
            cycle_id: currentCycle.id,
          }))
        );
      }
    }

    setPendingAllocations([]);
    toast({ title: 'Realocações aplicadas!', description: `${changedAllocations.length} membro(s) realocado(s).` });
    setOpen(false);
  };

  // === Auto suggestions using real data ===
  const generateAutoSuggestions = useCallback(async () => {
    if (!currentCycle || profiles.length === 0) return;
    setAutoLoading(true);

    const newIteration = autoIteration + 1;
    setAutoIteration(newIteration);

    const { data: allAllocationsData } = await supabase
      .from('member_allocations')
      .select('user_id, coordination_id, cycle_id');

    const allAllocsList = allAllocationsData || [];

    const historyMap = new Map<string, Set<string>>();
    allAllocsList.forEach(a => {
      if (!historyMap.has(a.user_id)) historyMap.set(a.user_id, new Set());
      historyMap.get(a.user_id)!.add(a.coordination_id);
    });

    const currentMap = new Map<string, string>();
    allocations.forEach(a => { currentMap.set(a.user_id, a.coordination_id); });

    const coordCounts = new Map<string, number>();
    allCoordinations.forEach(c => coordCounts.set(c.id, 0));
    allocations.forEach(a => {
      coordCounts.set(a.coordination_id, (coordCounts.get(a.coordination_id) || 0) + 1);
    });

    const newSuggestions: AutoSuggestion[] = [];
    const coordProfiles = profiles.filter(p => !isLeader(p.user_id));

    coordProfiles.forEach(profile => {
      const visited = historyMap.get(profile.user_id) || new Set<string>();
      const unvisited = allCoordinations.filter(c => !visited.has(c.id));
      const pool = unvisited.length > 0 ? unvisited : allCoordinations;

      const shuffled = [...pool].sort(() => Math.random() - 0.5);
      shuffled.sort((a, b) => {
        const countA = coordCounts.get(a.id) || 0;
        const countB = coordCounts.get(b.id) || 0;
        return (countA - countB) + (Math.random() - 0.5);
      });

      const currentCoordId = currentMap.get(profile.user_id) || null;
      const suggested = shuffled.find(c => c.id !== currentCoordId) || shuffled[0];

      const visitedCount = visited.size;
      const totalCoords = allCoordinations.length;
      const coverage = totalCoords > 0 ? (visitedCount / totalCoords) * 100 : 0;

      newSuggestions.push({
        userId: profile.user_id,
        userName: profile.display_name || profile.email.split('@')[0],
        currentCoordId,
        suggestedCoordId: suggested.id,
        reason: coverage < 30
          ? `Baixa cobertura (${visitedCount}/${totalCoords} coordenadorias). Recomendado para experiência 360°.`
          : coverage < 60
          ? `Cobertura média (${visitedCount}/${totalCoords}). Ainda não passou por ${suggested.name}.`
          : `Boa cobertura (${visitedCount}/${totalCoords}). Sugestão: ${suggested.name}.`,
        priority: coverage < 30 ? 'high' : coverage < 60 ? 'medium' : 'low',
      });
    });

    const priorityOrder = { high: 0, medium: 1, low: 2 };
    newSuggestions.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]);

    setAutoSuggestions(newSuggestions);
    setAutoGenerated(true);
    setAutoLoading(false);
  }, [profiles, allocations, currentCycle, autoIteration, positions]);

  const applyAutoSuggestion = async (suggestion: AutoSuggestion) => {
    if (!currentCycle) return;
    await saveAllocation(suggestion.userId, currentCycle.id, suggestion.suggestedCoordId);
    setAutoSuggestions(prev => prev.filter(s => s.userId !== suggestion.userId));
    await fetchAllocations();
  };

  const applyAllAutoSuggestions = async () => {
    if (!currentCycle) return;
    for (const s of autoSuggestions) {
      await saveAllocation(s.userId, currentCycle.id, s.suggestedCoordId);
    }
    setAutoSuggestions([]);
    await fetchAllocations();
    toast({ title: 'Todas as sugestões aplicadas', description: 'As alocações foram atualizadas.' });
    setOpen(false);
  };

  const priorityConfig = {
    high: { color: 'bg-destructive/10 text-destructive border-destructive/20', label: 'Alta' },
    medium: { color: 'bg-amber-500/10 text-amber-600 border-amber-500/20', label: 'Média' },
    low: { color: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20', label: 'Baixa' },
  };

  const changesCount = pendingAllocations.filter(p => hasChanges(p.userId)).length;

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="gap-2 bg-gradient-to-r from-primary to-accent hover:opacity-90" size="sm">
          <Shuffle className="w-4 h-4" />
          <span className="hidden sm:inline">Realocar</span>
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <Shuffle className="w-5 h-5 text-primary" />
            Realocação de Membros
          </DialogTitle>
          <DialogDescription>
            Gerencie a alocação dos coordenadores em coordenadorias e grupos de trabalho.
          </DialogDescription>
        </DialogHeader>

        <Tabs defaultValue="manual" className="flex-1 flex flex-col min-h-0">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="auto" className="gap-2">
              <Sparkles className="w-4 h-4" />
              <span className="hidden sm:inline">Sugestão Automática</span>
              <span className="sm:hidden">Auto</span>
            </TabsTrigger>
            <TabsTrigger value="manual" className="gap-2">
              <Users className="w-4 h-4" />
              <span className="hidden sm:inline">Alocação Manual</span>
              <span className="sm:hidden">Manual</span>
            </TabsTrigger>
          </TabsList>

          {/* Auto suggestions tab */}
          <TabsContent value="auto" className="flex-1 flex flex-col mt-4 min-h-0 data-[state=inactive]:hidden">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 mb-4 flex-shrink-0">
              <p className="text-sm text-muted-foreground">
                O sistema analisa o histórico e sugere realocações para maximizar a experiência 360°.
              </p>
              <Button variant="outline" size="sm" onClick={generateAutoSuggestions} disabled={autoLoading} className="gap-2 flex-shrink-0">
                {autoLoading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Gerando...
                  </>
                ) : autoGenerated ? (
                  <>
                    <RefreshCw className="w-4 h-4" />
                    Nova Sugestão
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    Gerar Sugestões
                  </>
                )}
              </Button>
            </div>

            <ScrollArea className="flex-1 min-h-[300px]">
              <div className="pr-4">
                {autoSuggestions.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-12 text-center">
                    <Sparkles className="w-12 h-12 text-muted-foreground/50 mb-4" />
                    <p className="text-muted-foreground">
                      Clique em "{autoGenerated ? 'Nova Sugestão' : 'Gerar Sugestões'}" para obter recomendações.
                    </p>
                  </div>
                ) : (
                  <div className="space-y-3">
                    {autoSuggestions.map((suggestion, index) => {
                      const currentCoord = suggestion.currentCoordId ? getCoordination(suggestion.currentCoordId) : null;
                      const suggestedCoord = getCoordination(suggestion.suggestedCoordId);
                      const priority = priorityConfig[suggestion.priority];

                      return (
                        <motion.div
                          key={suggestion.userId}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: index * 0.05 }}
                          className="p-4 rounded-lg border bg-card hover:bg-accent/5 transition-colors"
                        >
                          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                            <div className="flex items-center gap-3 flex-1 min-w-0">
                              <div className="flex-1 min-w-0">
                                <p className="font-medium truncate">{suggestion.userName}</p>
                                <div className="flex items-center gap-2 text-sm text-muted-foreground flex-wrap">
                                  <span className="truncate max-w-[100px]">{currentCoord?.name || 'Sem alocação'}</span>
                                  <ArrowRight className="w-4 h-4 flex-shrink-0 text-primary" />
                                  <span className="truncate max-w-[100px] font-medium text-foreground">
                                    {suggestedCoord?.name}
                                  </span>
                                </div>
                              </div>
                            </div>
                            <div className="flex items-center gap-2">
                              <Badge variant="outline" className={priority.color}>
                                {priority.label}
                              </Badge>
                              <Button
                                size="sm"
                                variant="ghost"
                                className="text-primary hover:text-primary hover:bg-primary/10"
                                onClick={() => applyAutoSuggestion(suggestion)}
                              >
                                <Check className="w-4 h-4" />
                              </Button>
                            </div>
                          </div>
                          <p className="text-xs text-muted-foreground mt-2">{suggestion.reason}</p>
                        </motion.div>
                      );
                    })}
                  </div>
                )}
              </div>
            </ScrollArea>

            {autoSuggestions.length > 0 && (
              <DialogFooter className="mt-4 pt-4 border-t flex-col sm:flex-row gap-2">
                <Button variant="outline" onClick={() => setOpen(false)} className="w-full sm:w-auto">
                  Cancelar
                </Button>
                <Button onClick={applyAllAutoSuggestions} className="gap-2 w-full sm:w-auto">
                  <Check className="w-4 h-4" />
                  Aplicar Todas ({autoSuggestions.length})
                </Button>
              </DialogFooter>
            )}
          </TabsContent>

          {/* Manual allocation tab */}
          <TabsContent value="manual" className="flex-1 flex flex-col mt-4 min-h-0 data-[state=inactive]:hidden overflow-hidden">
            <p className="text-sm text-muted-foreground mb-4 flex-shrink-0">
              Selecione a coordenadoria e/ou grupos de trabalho para cada coordenador.
            </p>

            <div className="flex-1 overflow-y-auto min-h-0 max-h-[400px]">
              <div className="space-y-3 pr-4">
                {coordinatorProfiles.map((profile, index) => {
                  const displayCoordId = getDisplayCoordId(profile.user_id);
                  const displayGTs = getDisplayGTs(profile.user_id);
                  const status = getAllocationStatus(profile.user_id);
                  const changed = hasChanges(profile.user_id);

                  return (
                    <motion.div
                      key={profile.user_id}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.02 }}
                      className={`p-4 rounded-lg border transition-colors ${
                        changed ? 'bg-primary/5 border-primary/30' : 'bg-card'
                      }`}
                    >
                      <div className="flex flex-col gap-3">
                        <div className="flex items-center gap-3">
                          <Avatar className="h-10 w-10 shrink-0">
                            <AvatarImage src={profile.avatar_url || undefined} />
                            <AvatarFallback>
                              {getInitials(profile.display_name, profile.email)}
                            </AvatarFallback>
                          </Avatar>
                          <div className="flex-1 min-w-0">
                            <p className="font-medium truncate">{profile.display_name || profile.email}</p>
                            <div className="flex items-center gap-2">
                              <Badge 
                                variant={status === 'complete' ? 'default' : status === 'partial' ? 'secondary' : 'outline'}
                                className="text-xs"
                              >
                                {status === 'complete' ? 'Completo' : status === 'partial' ? 'Parcial' : 'Pendente'}
                              </Badge>
                              {status === 'partial' && (
                                <AlertCircle className="w-3 h-3 text-amber-500" />
                              )}
                            </div>
                          </div>
                        </div>

                        {/* Coordination */}
                        <div className="space-y-1">
                          <label className="text-xs text-muted-foreground flex items-center gap-1">
                            <Building2 className="w-3 h-3" />
                            Coordenadoria
                          </label>
                          <Select
                            value={displayCoordId || '__none__'}
                            onValueChange={(value) => handleCoordChange(profile.user_id, value)}
                          >
                            <SelectTrigger className="h-9 text-sm">
                              <SelectValue placeholder="Selecionar..." />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="__none__">Nenhuma</SelectItem>
                              {allCoordinations.map((coord) => (
                                <SelectItem key={coord.id} value={coord.id}>
                                  <span className="truncate">{coord.name}</span>
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>

                        {/* Multi-GT */}
                        <div className="space-y-2">
                          <div className="flex items-center justify-between">
                            <label className="text-xs text-muted-foreground flex items-center gap-1">
                              <Briefcase className="w-3 h-3" />
                              Grupos de Trabalho ({displayGTs.length})
                            </label>
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-6 px-2 text-xs gap-1"
                              onClick={() => handleAddGT(profile.user_id)}
                            >
                              <Plus className="w-3 h-3" />
                              Adicionar GT
                            </Button>
                          </div>

                          {displayGTs.length === 0 && (
                            <p className="text-xs text-muted-foreground italic">Nenhum GT atribuído</p>
                          )}

                          {displayGTs.map((gt, idx) => (
                            <div key={idx} className="flex items-center gap-2">
                              <Select
                                value={gt.client_id || '__none__'}
                                onValueChange={(v) => handleGTClientChange(profile.user_id, idx, v === '__none__' ? '' : v)}
                              >
                                <SelectTrigger className="flex-1 h-8 text-sm">
                                  <SelectValue placeholder="Cliente...">
                                    {gt.client_id ? getClientName(gt.client_id) : 'Cliente...'}
                                  </SelectValue>
                                </SelectTrigger>
                                <SelectContent>
                                  {clients.map((client) => (
                                    <SelectItem key={client.id} value={client.id}>
                                      {client.name}
                                    </SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                              <Select
                                value={gt.role || 'consultant'}
                                onValueChange={(v) => handleGTRoleChange(profile.user_id, idx, v)}
                              >
                                <SelectTrigger className="w-32 h-8 text-sm">
                                  <SelectValue>{getRoleLabel(gt.role)}</SelectValue>
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="director">Diretor</SelectItem>
                                  <SelectItem value="manager">Gerente</SelectItem>
                                  <SelectItem value="consultant">Consultor</SelectItem>
                                </SelectContent>
                              </Select>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8 text-destructive hover:text-destructive"
                                onClick={() => handleRemoveGT(profile.user_id, idx)}
                              >
                                <X className="w-3 h-3" />
                              </Button>
                            </div>
                          ))}
                        </div>
                      </div>
                    </motion.div>
                  );
                })}
              </div>
            </div>

            <DialogFooter className="mt-4 pt-4 border-t flex-col sm:flex-row gap-2">
              <div className="flex items-center gap-2 sm:mr-auto w-full sm:w-auto justify-center sm:justify-start">
                {changesCount > 0 && (
                  <Badge variant="secondary" className="gap-1">
                    {changesCount} alteração(ões) pendente(s)
                  </Badge>
                )}
              </div>
              <Button variant="outline" onClick={() => setOpen(false)} className="w-full sm:w-auto">
                Cancelar
              </Button>
              <Button
                onClick={applyManualAllocations}
                disabled={changesCount === 0}
                className="gap-2 w-full sm:w-auto"
              >
                <Check className="w-4 h-4" />
                Aplicar Alterações
              </Button>
            </DialogFooter>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
};